"""Read-only normalized observations for future Nuzlocke domain code."""

from .snapshots import (
    BattleSnapshot,
    BattlePokemonSnapshot,
    ItemQuantity,
    InventorySnapshot,
    MoveSnapshot,
    NamedFlag,
    NamedVariable,
    CampaignObservationSnapshot,
    NuzlockeSnapshot,
    PartyPokemonSnapshot,
    PlayerSnapshot,
    ProgressionSnapshot,
    PokemonSnapshot,
    StorageSnapshot,
    StoragePokemonSnapshot,
    get_nuzlocke_snapshot,
)
from .identity import PokemonIdentity
from .events import NuzlockeStarted, PokemonCaptured, PokemonStorageLocation, StorageChanged
from .runtime import NuzlockeRuntime
from .policy import EventStatistics, PersistenceClass, classify_event
from .diagnostics import BoundedEventTrace
from .persistence import (
    EventStoreCorruptionError,
    EventStoreError,
    JsonEventStore,
    deserialize_event,
    serialize_event,
)
from .projection import (
    CampaignProjection,
    ObservedBattle,
    ObservedCampaignState,
    ObservedEvent,
    ObservedPokemon,
    load_campaign_projection,
    reduce_events,
)
from .rules import (
    NuzlockeCampaignState,
    NuzlockeRulesProjection,
    LocationEncounter,
    RuleViolation,
    load_rules,
    reduce_rules,
)
from .campaign_state import CampaignFacts, CampaignState, Fact, FactStatus, RunStatus, derive_campaign_facts
from .campaign_objectives import (
    CampaignObjective,
    CampaignPredicate,
    ObjectiveSelection,
    ObjectiveStatus,
    initial_emerald_campaign,
    select_campaign_objective,
)
from .campaign_execution import (
    CampaignExecutionAdapter,
    CampaignExecutionResult,
    CampaignExecutionStatus,
    adapt_campaign_execution,
)
from .campaign_controller import CampaignController, CampaignControllerState, CampaignControllerStatus
from .resource_policy import (
    EncounterPolicy,
    HealingResource,
    PartyResource,
    ReadinessImportance,
    ResourceDecision,
    ResourceObjective,
    ResourceSnapshot,
    RouteRecovery,
    assess_campaign_resources,
    assess_wild_encounter,
)

__all__ = [
    "BattleSnapshot",
    "BattlePokemonSnapshot",
    "ItemQuantity",
    "InventorySnapshot",
    "MoveSnapshot",
    "NamedFlag",
    "NamedVariable",
    "CampaignObservationSnapshot",
    "NuzlockeSnapshot",
    "PartyPokemonSnapshot",
    "PlayerSnapshot",
    "ProgressionSnapshot",
    "PokemonSnapshot",
    "StorageSnapshot",
    "StoragePokemonSnapshot",
    "PokemonIdentity",
    "PokemonStorageLocation",
    "StorageChanged",
    "PokemonCaptured",
    "NuzlockeStarted",
    "get_nuzlocke_snapshot",
    "NuzlockeRuntime",
    "PersistenceClass",
    "EventStatistics",
    "classify_event",
    "BoundedEventTrace",
    "EventStoreError",
    "EventStoreCorruptionError",
    "JsonEventStore",
    "serialize_event",
    "deserialize_event",
    "CampaignProjection",
    "ObservedBattle",
    "ObservedCampaignState",
    "ObservedEvent",
    "ObservedPokemon",
    "load_campaign_projection",
    "reduce_events",
    "NuzlockeCampaignState",
    "NuzlockeRulesProjection",
    "LocationEncounter",
    "RuleViolation",
    "load_rules",
    "reduce_rules",
    "CampaignState",
    "Fact",
    "FactStatus",
    "RunStatus",
    "CampaignFacts",
    "derive_campaign_facts",
    "CampaignObjective",
    "CampaignPredicate",
    "ObjectiveSelection",
    "ObjectiveStatus",
    "initial_emerald_campaign",
    "select_campaign_objective",
    "CampaignExecutionAdapter",
    "CampaignExecutionResult",
    "CampaignExecutionStatus",
    "adapt_campaign_execution",
    "CampaignController",
    "CampaignControllerState",
    "CampaignControllerStatus",
]
