"""Application-level delivery for normalized Nuzlocke observations.

This module is the boundary between the frame loop and the domain observer.
It reads no emulator state itself: callers provide a snapshot (or a snapshot
provider), and consumers receive immutable events in frame order.
"""

from __future__ import annotations

from collections import deque
from collections.abc import Callable
from uuid import uuid4
from typing import TYPE_CHECKING

from .events import Event, NuzlockeEventObserver
from .snapshots import NuzlockeSnapshot, get_nuzlocke_snapshot

if TYPE_CHECKING:
    from typing import Deque


class NuzlockeRuntime:
    """Feed one snapshot per application frame and expose each event once."""

    def __init__(
        self,
        snapshot_provider: Callable[[], NuzlockeSnapshot] = get_nuzlocke_snapshot,
        event_sink: Callable[[Event, str], None] | None = None,
        session_id: str | None = None,
    ) -> None:
        self._snapshot_provider = snapshot_provider
        self._event_sink = event_sink
        self._session_id = session_id or str(uuid4())
        self._event_sequence = 0
        self._observer = NuzlockeEventObserver()
        self._events: Deque[Event] = deque()
        self._subscribers: list[Callable[[Event], None]] = []
        self._last_frame: int | None = None

    def update(self, snapshot: NuzlockeSnapshot | None = None) -> tuple[Event, ...]:
        """Process the current frame and return events generated by it.

        A backwards frame count denotes a reset or save-state load.  The
        observer is replaced and the current snapshot becomes a new baseline,
        so the reset cannot manufacture transitions between unrelated states.
        """
        trace = getattr(__import__("modules.context", fromlist=["context"]), "context", None)
        trace = getattr(trace, "stutter_trace", None)
        observe_started = trace.now() if trace is not None else 0
        current = self._snapshot_provider() if snapshot is None else snapshot
        if trace is not None:
            trace.duration("nuzlocke_observer_duration_ms", observe_started)
        if self._last_frame is not None and current.frame < self._last_frame:
            self._observer = NuzlockeEventObserver()
            self._events.clear()
            self._session_id = str(uuid4())
            self._event_sequence = 0

        self._last_frame = current.frame
        observer_started = trace.now() if trace is not None else 0
        events = self._observer.observe(current)
        if trace is not None:
            trace.duration("nuzlocke_observer_duration_ms", observer_started)
        self._events.extend(events)
        for event in events:
            self._event_sequence += 1
            if self._event_sink is not None:
                self._event_sink(event, self._session_id)
            for subscriber in tuple(self._subscribers):
                subscriber(event)
        return events

    @property
    def session_id(self) -> str:
        """Identifier for this emulator timeline, including reset boundaries."""
        return self._session_id

    def subscribe(self, consumer: Callable[[Event], None]) -> Callable[[], None]:
        """Register a synchronous consumer and return its unsubscribe action."""
        self._subscribers.append(consumer)

        def unsubscribe() -> None:
            if consumer in self._subscribers:
                self._subscribers.remove(consumer)

        return unsubscribe

    def drain_events(self) -> tuple[Event, ...]:
        """Return queued events in order, removing them from the runtime."""
        events = tuple(self._events)
        self._events.clear()
        return events
