"""Application-level delivery for normalized Nuzlocke observations.

This module is the boundary between the frame loop and the domain observer.
It reads no emulator state itself: callers provide a snapshot (or a snapshot
provider), and consumers receive immutable events in frame order.
"""

from __future__ import annotations

from collections import deque
from collections.abc import Callable
from uuid import uuid4
from typing import TYPE_CHECKING

from .events import Event, NuzlockeEventObserver, NuzlockeStarted
from .policy import EventSink, EventStatistics, PersistenceClass, classify_event
from .snapshots import NuzlockeSnapshot, get_nuzlocke_snapshot
from .projection import CampaignProjection
from .rules import NuzlockeRulesProjection

if TYPE_CHECKING:
    from typing import Deque


class NuzlockeRuntime:
    """Feed one snapshot per application frame and expose each event once."""

    def __init__(
        self,
        snapshot_provider: Callable[[], NuzlockeSnapshot] = get_nuzlocke_snapshot,
        event_sink: EventSink | None = None,
        diagnostic_sink: EventSink | None = None,
        session_id: str | None = None,
    ) -> None:
        self._snapshot_provider = snapshot_provider
        self._event_sink = event_sink
        self._diagnostic_sink = diagnostic_sink
        self._session_id = session_id or str(uuid4())
        self._event_sequence = 0
        self._observer = NuzlockeEventObserver()
        self._events: Deque[Event] = deque()
        self._subscribers: list[Callable[[Event], None]] = []
        self._last_frame: int | None = None
        self._campaign_projection = CampaignProjection()
        self._rules_projection = NuzlockeRulesProjection(encounters_active=False)
        self._event_statistics = EventStatistics()

    @property
    def observed_projection(self) -> CampaignProjection:
        return self._campaign_projection

    @property
    def rules_projection(self) -> NuzlockeRulesProjection:
        return self._rules_projection

    def update(self, snapshot: NuzlockeSnapshot | None = None) -> tuple[Event, ...]:
        """Process the current frame and return events generated by it.

        A backwards frame count denotes a reset or save-state load.  The
        observer is replaced and the current snapshot becomes a new baseline,
        so the reset cannot manufacture transitions between unrelated states.
        """
        trace = getattr(__import__("modules.context", fromlist=["context"]), "context", None)
        trace = getattr(trace, "stutter_trace", None)
        observe_started = trace.now() if trace is not None else 0
        current = self._snapshot_provider() if snapshot is None else snapshot
        if trace is not None:
            trace.duration("nuzlocke_observer_duration_ms", observe_started)
        if self._last_frame is not None and current.frame < self._last_frame:
            self._observer = NuzlockeEventObserver()
            self._campaign_projection = CampaignProjection()
            self._rules_projection = NuzlockeRulesProjection(encounters_active=False)
            self._events.clear()
            self._session_id = str(uuid4())
            self._event_sequence = 0

        self._last_frame = current.frame
        balls = sum(item.quantity for item in current.inventory.poke_balls)
        if current.inventory_available and balls > 0:
            self._rules_projection.set_encounters_active(True)
        observer_started = trace.now() if trace is not None else 0
        events = self._observer.observe(current)
        if trace is not None:
            trace.duration("nuzlocke_observer_duration_ms", observer_started)
        for event in events:
            self._event_sequence += 1
            self._campaign_projection.apply(event, session_id=self._session_id, sequence=self._event_sequence)
            self._rules_projection.apply(event, sequence=self._event_sequence)
            persistence_class = classify_event(event)
            self._event_statistics.record(event, persistence_class)
            if persistence_class is PersistenceClass.DURABLE and self._event_sink is not None:
                self._event_sink(event, self._session_id)
            elif persistence_class is PersistenceClass.DIAGNOSTIC and self._diagnostic_sink is not None:
                self._diagnostic_sink(event, self._session_id)
            for subscriber in tuple(self._subscribers):
                subscriber(event)
        self._events.extend(events)
        return events

    def event_statistics(self) -> dict[str, dict[str, int]]:
        """Return generated-event counts grouped by persistence class/type."""
        return self._event_statistics.snapshot()

    @property
    def session_id(self) -> str:
        """Identifier for this emulator timeline, including reset boundaries."""
        return self._session_id

    def subscribe(self, consumer: Callable[[Event], None]) -> Callable[[], None]:
        """Register a synchronous consumer and return its unsubscribe action."""
        self._subscribers.append(consumer)

        def unsubscribe() -> None:
            if consumer in self._subscribers:
                self._subscribers.remove(consumer)

        return unsubscribe

    def drain_events(self) -> tuple[Event, ...]:
        """Return queued events in order, removing them from the runtime."""
        events = tuple(self._events)
        self._events.clear()
        return events

    def mark_nuzlocke_started(self, frame: int | None = None) -> NuzlockeStarted | None:
        """Record Nuzbot's campaign boundary without inventing gameplay."""
        if self._campaign_projection.state.nuzlocke_started:
            return None
        event = NuzlockeStarted(self._last_frame if frame is None else frame)
        self._event_sequence += 1
        self._campaign_projection.apply(event, session_id=self._session_id, sequence=self._event_sequence)
        self._rules_projection.apply(event, sequence=self._event_sequence)
        if self._event_sink is not None:
            self._event_sink(event, self._session_id)
        self._event_statistics.record(event, PersistenceClass.DURABLE)
        for subscriber in tuple(self._subscribers):
            subscriber(event)
        self._events.append(event)
        return event
